// Fabric v5 → v6 shim. v6 dropped the `fabric` namespace export, so
// this re-exports v6's named exports under the legacy `fabric.X` shape
// our call sites use. Tree-shaking still works.
import {
  Canvas,
  StaticCanvas,
  ActiveSelection,
  Circle,
  Color,
  Control,
  Ellipse,
  FabricImage,
  FabricObject,
  FabricText,
  Gradient,
  Group,
  IText,
  Line,
  Path,
  Pattern,
  PencilBrush,
  Point,
  Polygon,
  Polyline,
  Rect,
  Shadow,
  Textbox,
  Triangle,
  classRegistry,
  config,
  controlsUtils,
  filters,
  loadSVGFromString,
  loadSVGFromURL,
  util,
  version,
} from "fabric";

// v5-style namespace; only the classes used in src/pages/Content/canvas.
export const fabric = {
  Canvas,
  StaticCanvas,
  ActiveSelection,
  Circle,
  Color,
  Control,
  Ellipse,
  Image: FabricImage,
  FabricImage,
  Object: FabricObject,
  FabricObject,
  Text: FabricText,
  FabricText,
  Gradient,
  Group,
  IText,
  Line,
  Path,
  Pattern,
  PencilBrush,
  Point,
  Polygon,
  Polyline,
  Rect,
  Shadow,
  Textbox,
  Triangle,
  classRegistry,
  config,
  controlsUtils,
  filters,
  loadSVGFromString,
  loadSVGFromURL,
  util,
  version,
};

export default fabric;
